#!/usr/bin/env bash
# Generate a large, clean-compiling multi-module Kotlin project for benchmarking ktlsp's
# diagnostics backends. The point is scale: the committed dev/ fixtures (13 and 2 files) are too
# small to expose the regime where Gradle's config/task-graph overhead and a backend's
# incrementality (or lack of it) actually diverge. This synthesizes that regime on demand.
#
# Dial the size with env vars (or the first two positional args):
#   NUM_MODULES        number of Gradle modules        (default 8,  or $1)
#   FILES_PER_MODULE   .kt files per module            (default 50, or $2)
#
# Examples:
#   dev/gen-bench-fixture.sh                 # 8 modules x 50 files = 400 .kt
#   dev/gen-bench-fixture.sh 8 80            # 8 x 80 = 640 .kt
#   NUM_MODULES=2 FILES_PER_MODULE=3 dev/gen-bench-fixture.sh
#
# Module mN (N>0) depends on m(N-1) via implementation(project(":m{N-1}")), and each module's
# Bridge.kt references a class from its dependency module, so an edit to a base module ripples
# across the module boundary. Module m0 additionally pulls real third-party deps (kotlinx
# coroutines + okio) so classpath resolution is realistic, not stdlib-only.
#
# Output goes to dev/bench-fixture/ (gitignored). Regeneration is idempotent: the output tree is
# wiped first, so changing the dials never leaves stale modules behind.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
out="$here/bench-fixture"
template="$here/gradle-wrapper-template"

NUM_MODULES="${NUM_MODULES:-${1:-8}}"
FILES_PER_MODULE="${FILES_PER_MODULE:-${2:-50}}"

if [ "$NUM_MODULES" -lt 1 ] || [ "$FILES_PER_MODULE" -lt 1 ]; then
  echo "NUM_MODULES and FILES_PER_MODULE must both be >= 1" >&2
  exit 2
fi
if [ ! -f "$template/gradlew" ]; then
  echo "missing wrapper template at $template (run Unit 1 wrapper bootstrap first)" >&2
  exit 2
fi

# Idempotent regenerate: wipe everything except a warm Gradle cache (.gradle) if one exists, so
# repeated runs during benchmarking don't re-download the distribution.
if [ -d "$out" ]; then
  find "$out" -mindepth 1 -maxdepth 1 -not -name '.gradle' -exec rm -rf {} +
fi
mkdir -p "$out"

# --- pinned wrapper ---------------------------------------------------------
cp "$template/gradlew" "$out/gradlew"
cp "$template/gradlew.bat" "$out/gradlew.bat"
mkdir -p "$out/gradle/wrapper"
cp "$template/gradle/wrapper/gradle-wrapper.jar" "$out/gradle/wrapper/gradle-wrapper.jar"
cp "$template/gradle/wrapper/gradle-wrapper.properties" "$out/gradle/wrapper/gradle-wrapper.properties"
chmod +x "$out/gradlew"

# --- settings + root build --------------------------------------------------
{
  echo 'rootProject.name = "bench-fixture"'
  echo -n 'include('
  for ((m = 0; m < NUM_MODULES; m++)); do
    [ "$m" -gt 0 ] && echo -n ', '
    echo -n "\":m$m\""
  done
  echo ')'
} > "$out/settings.gradle.kts"

cat > "$out/build.gradle.kts" <<'EOF'
// Generated by dev/gen-bench-fixture.sh — do not edit by hand.
plugins {
    kotlin("jvm") version "2.1.20" apply false
}

subprojects {
    repositories {
        mavenCentral()
    }
}
EOF

# --- per-module sources -----------------------------------------------------
for ((m = 0; m < NUM_MODULES; m++)); do
  mod="$out/m$m"
  pkgdir="$mod/src/main/kotlin/com/example/bench/m$m"
  mkdir -p "$pkgdir"

  # build.gradle.kts: m0 carries real third-party deps; mN (N>0) depends on m(N-1).
  if [ "$m" -eq 0 ]; then
    cat > "$mod/build.gradle.kts" <<'EOF'
plugins {
    kotlin("jvm")
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")
    implementation("com.squareup.okio:okio:3.9.1")
}
EOF
  else
    cat > "$mod/build.gradle.kts" <<EOF
plugins {
    kotlin("jvm")
}

dependencies {
    implementation(project(":m$((m - 1))"))
}
EOF
  fi

  # Leaf files: self-contained classes (editing one is a cheap, module-local recompile).
  for ((f = 0; f < FILES_PER_MODULE; f++)); do
    cat > "$pkgdir/M${m}F${f}.kt" <<EOF
package com.example.bench.m$m

class M${m}F${f} {
    fun value(): Int = $f
    fun combine(x: Int): Int = value() + x
    fun label(): String = "m${m}f${f}:" + value().toString()
}
EOF
  done

  # Bridge file: crosses the module boundary (editing a base module's class ripples here on
  # recompile). m0 instead exercises the third-party classpath.
  if [ "$m" -eq 0 ]; then
    cat > "$pkgdir/Bridge.kt" <<EOF
package com.example.bench.m0

import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.delay
import okio.Buffer

class Bridge {
    fun viaCoroutines(): Int = runBlocking {
        delay(1)
        M0F0().value()
    }

    fun viaOkio(): String = Buffer().writeUtf8("m0").readUtf8()
}
EOF
  else
    cat > "$pkgdir/Bridge.kt" <<EOF
package com.example.bench.m$m

import com.example.bench.m$((m - 1)).M$((m - 1))F0

class Bridge {
    fun call(): Int = M$((m - 1))F0().value() + M${m}F0().value()
}
EOF
  fi
done

total_files=$(find "$out" -name '*.kt' | wc -l | tr -d ' ')
echo "generated $out"
echo "  modules: $NUM_MODULES  files/module: $FILES_PER_MODULE  total .kt: $total_files"
echo "  build:   (cd $out && ./gradlew compileKotlin --console=plain --continue)"
